export const CITIES = [
  { value: "MOSCOW", label: "Москва" },
  { value: "SAINT_PETERSBURG", label: "Санкт-Петербург" },
  { value: "KAZAN", label: "Казань" },
  { value: "SOCHI", label: "Сочи" },
  { value: "NIZHNY_NOVGOROD", label: "Нижний Новгород" },
  { value: "VLADIVOSTOK", label: "Владивосток" },
  { value: "NOVOSIBIRSK", label: "Новосибирск" },
  { value: "YEKATERINBURG", label: "Екатеринбург" },
  { value: "KALININGRAD", label: "Калининград" },
  { value: "YAROSLAVL", label: "Ярославль" },
  { value: "SMOLENSK", label: "Смоленск" },
  { value: "VELIKY_NOVGOROD", label: "Великий Новгород" },
  { value: "KRASNODAR", label: "Краснодар" },
  { value: "IRKUTSK", label: "Иркутск" },
  { value: "TOBOLSK", label: "Тобольск" },
  { value: "PSKOV", label: "Псков" },
  { value: "SAMARA", label: "Самара" },
  { value: "MURMANSK", label: "Мурманск" },
  { value: "VOLGOGRAD", label: "Волгоград" },
  { value: "UFA", label: "Уфа" },
  { value: "KOLOMNA", label: "Коломна" },
  { value: "KRASNOYARSK", label: "Красноярск" },
  { value: "DERBENT", label: "Дербент" },
  { value: "GELENDZHIK", label: "Геленджик" },
  { value: "ANAPA", label: "Анапа" },
  { value: "YELETS", label: "Елец" },
  { value: "SEMENOV", label: "Семёнов" },
  { value: "KUDYMKAR", label: "Кудымкар" },
  { value: "YOSHKAR_OLA", label: "Йошкар-Ола" },
  { value: "SARANSK", label: "Саранск" },
  { value: "TULA", label: "Тула" },
  { value: "VLADIMIR", label: "Владимир" },
  { value: "SUZDAL", label: "Суздаль" },
  { value: "SERGIEV_POSAD", label: "Сергиев Посад" },
  { value: "ROSTOV_VELIKY", label: "Ростов Великий" },
  { value: "PERESLAVL_ZALESSKY", label: "Переславль-Залесский" },
  { value: "UGLICH", label: "Углич" },
  { value: "KOSTROMA", label: "Кострома" },
  { value: "BERDYANSK", label: "Бердянск" },
  { value: "KAMENSK_URALSKY", label: "Каменск-Уральский" },
  { value: "FEODOSIA", label: "Феодосия" },
  { value: "TUAPSE", label: "Туапсе" },
  { value: "YEYSK", label: "Ейск" },
  { value: "NOVOROSSIYSK", label: "Новороссийск" },
  { value: "PYATIGORSK", label: "Пятигорск" },
  { value: "KISLOVODSK", label: "Кисловодск" }
];